services: 
  postgres: 
    image: postgres:17.6-bookworm 
    container_name: postgres 
    env_file: 
      - postgres.env 
    environment: 
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: ${POSTGRES_DB} 
    ports: 
      - "5432:5432" 
    volumes: 
      - postgres_data:/var/lib/postgresql/data 
    networks: 
      - postgres_network 
 
  pgadmin: 
    image: dpage/pgadmin4:9.8.0 
    container_name: pgadmin4 
    env_file: 
      - postgres.env 
    environment: 
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL} 
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD} 
      PGADMIN_LISTEN_PORT: 5454 
    ports: 
      - "5454:5454" 
    networks: 
      - postgres_network 
    depends_on: 
      - postgres
 
volumes: 
  postgres_data: 
    driver: local 
 
networks: 
  postgres_network: 
    driver: bridge